version: '3.8'
services:
  db-meuremedio:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "meuremediobd"
    networks:
      - backend
    ports:
      - 5432:5432
    expose:
      - 5432


  app-meuremedio:
    container_name: meuremedio
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - db-meuremedio

networks:
  backend:
    driver: bridge