apiVersion: v1
kind: Pod
metadata:
  name: meuremedio-pod
  labels:
    app: meuremedio
spec:
  containers:
    - name: db-meuremedio
      image: postgres:15.1-alpine
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "root"
        - name: POSTGRES_DB
          value: "meuremediobd"
      ports:
        - containerPort: 5432
      resources:
        limits:
          memory: "1Gi"
          cpu: "500m"
    - name: app-meuremedio
      image: lucaskubo/meu-remedio:1.2
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: "1Gi"
          cpu: "500m"
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "root"
        - name: POSTGRES_DB
          value: "meuremediobda"
        - name: POSTGRES_HOST
          value: "db-meuremedioa"
  restartPolicy: Always