apiVersion: v1
kind: Service
metadata:
  name: meuremedio-service
spec:
  type: NodePort
  selector:
    app: meuremedio
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000